# Generated by Django 4.0.5 on 2022-06-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiretorioJornalistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='estado_civil',
            field=models.IntegerField(choices=[(3, 'Divorciado'), (5, 'União Estável'), (1, 'Solteiro'), (4, 'Viúvo'), (2, 'Casado')]),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(2, 'Masculino'), (1, 'Femino'), (3, 'Não Binário')], null=True),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='raca',
            field=models.IntegerField(choices=[(2, 'Branca'), (4, 'Parda'), (3, 'Amarela (Origem Asiática/Oriental)'), (6, 'Não Declarado'), (5, 'Indígena'), (1, 'Preta')]),
        ),
        migrations.AlterField(
            model_name='redesocial',
            name='tipo',
            field=models.IntegerField(choices=[(7, 'Twitter'), (4, 'Instagram'), (2, 'Facebook'), (6, 'LinkedIn'), (8, 'OUtras'), (3, 'Youtube'), (5, 'PodCast'), (1, 'Site/Blog')]),
        ),
        migrations.AlterField(
            model_name='veiculodecomunicacao',
            name='tipo',
            field=models.IntegerField(choices=[(6, 'Rede Social'), (3, 'Rádio'), (1, 'Jornal'), (4, 'TV'), (7, 'Plataforma de Video'), (2, 'Revista'), (5, 'Site/Blog'), (8, 'Podcast')]),
        ),
    ]
