# Generated by Django 4.0.5 on 2022-06-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiretorioJornalistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='estado_civil',
            field=models.IntegerField(choices=[(3, 'Divorciado'), (4, 'Viúvo'), (2, 'Casado'), (5, 'União Estável'), (1, 'Solteiro')]),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(1, 'Femino'), (2, 'Masculino'), (3, 'Não Binário')], null=True),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='raca',
            field=models.IntegerField(choices=[(2, 'Branca'), (6, 'Não Declarado'), (3, 'Amarela (Origem Asiática/Oriental)'), (5, 'Indígena'), (1, 'Preta'), (4, 'Parda')]),
        ),
        migrations.AlterField(
            model_name='redesocial',
            name='tipo',
            field=models.IntegerField(choices=[(5, 'PodCast'), (2, 'Facebook'), (3, 'Youtube'), (8, 'OUtras'), (6, 'LinkedIn'), (4, 'Instagram'), (7, 'Twitter'), (1, 'Site/Blog')]),
        ),
        migrations.AlterField(
            model_name='veiculodecomunicacao',
            name='tipo',
            field=models.IntegerField(choices=[(3, 'Rádio'), (8, 'Podcast'), (2, 'Revista'), (6, 'Rede Social'), (5, 'Site/Blog'), (7, 'Plataforma de Video'), (4, 'TV'), (1, 'Jornal')]),
        ),
    ]
