# Generated by Django 4.0.5 on 2022-06-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiretorioJornalistas', '0002_alter_jornalista_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='estado_civil',
            field=models.IntegerField(choices=[(5, 'União Estável'), (1, 'Solteiro'), (2, 'Casado'), (4, 'Viúvo'), (3, 'Divorciado')]),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(3, 'Não Binário'), (2, 'Masculino'), (1, 'Femino')], null=True),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='raca',
            field=models.IntegerField(choices=[(3, 'Amarela (Origem Asiática/Oriental)'), (5, 'Indígena'), (1, 'Preta'), (6, 'Não Declarado'), (4, 'Parda'), (2, 'Branca')]),
        ),
        migrations.AlterField(
            model_name='redesocial',
            name='tipo',
            field=models.IntegerField(choices=[(4, 'Instagram'), (8, 'OUtras'), (2, 'Facebook'), (5, 'PodCast'), (6, 'LinkedIn'), (7, 'Twitter'), (3, 'Youtube'), (1, 'Site/Blog')]),
        ),
        migrations.AlterField(
            model_name='veiculodecomunicacao',
            name='tipo',
            field=models.IntegerField(choices=[(8, 'Podcast'), (1, 'Jornal'), (2, 'Revista'), (4, 'TV'), (7, 'Plataforma de Video'), (3, 'Rádio'), (5, 'Site/Blog'), (6, 'Rede Social')]),
        ),
    ]
