# Generated by Django 4.0.5 on 2022-07-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiretorioJornalistas', '0003_alter_jornalista_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='estado_civil',
            field=models.IntegerField(choices=[(2, 'Casado'), (3, 'Divorciado'), (4, 'Viúvo'), (1, 'Solteiro'), (5, 'União Estável')]),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(2, 'Masculino'), (3, 'Não Binário'), (1, 'Femino')], null=True),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='raca',
            field=models.IntegerField(choices=[(1, 'Preta'), (4, 'Parda'), (3, 'Amarela (Origem Asiática/Oriental)'), (6, 'Não Declarado'), (5, 'Indígena'), (2, 'Branca')]),
        ),
        migrations.AlterField(
            model_name='redesocial',
            name='tipo',
            field=models.IntegerField(choices=[(2, 'Facebook'), (3, 'Youtube'), (7, 'Twitter'), (1, 'Site/Blog'), (4, 'Instagram'), (8, 'OUtras'), (6, 'LinkedIn'), (5, 'PodCast')]),
        ),
        migrations.AlterField(
            model_name='veiculodecomunicacao',
            name='tipo',
            field=models.IntegerField(choices=[(3, 'Rádio'), (5, 'Site/Blog'), (7, 'Plataforma de Video'), (6, 'Rede Social'), (1, 'Jornal'), (2, 'Revista'), (8, 'Podcast'), (4, 'TV')]),
        ),
    ]
