# Generated by Django 4.0.5 on 2022-07-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiretorioJornalistas', '0005_alter_jornalista_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='estado_civil',
            field=models.IntegerField(choices=[(4, 'Viúvo'), (1, 'Solteiro'), (3, 'Divorciado'), (2, 'Casado'), (5, 'União Estável')]),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(1, 'Femino'), (3, 'Não Binário'), (2, 'Masculino')], null=True),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='raca',
            field=models.IntegerField(choices=[(1, 'Preta'), (3, 'Amarela (Origem Asiática/Oriental)'), (5, 'Indígena'), (2, 'Branca'), (4, 'Parda'), (6, 'Não Declarado')]),
        ),
        migrations.AlterField(
            model_name='redesocial',
            name='tipo',
            field=models.IntegerField(choices=[(2, 'Facebook'), (6, 'LinkedIn'), (8, 'OUtras'), (5, 'PodCast'), (4, 'Instagram'), (3, 'Youtube'), (7, 'Twitter'), (1, 'Site/Blog')]),
        ),
        migrations.AlterField(
            model_name='veiculodecomunicacao',
            name='tipo',
            field=models.IntegerField(choices=[(7, 'Plataforma de Video'), (3, 'Rádio'), (1, 'Jornal'), (4, 'TV'), (2, 'Revista'), (5, 'Site/Blog'), (6, 'Rede Social'), (8, 'Podcast')]),
        ),
    ]
