# Generated by Django 4.0.5 on 2022-07-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiretorioJornalistas', '0006_alter_jornalista_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='estado_civil',
            field=models.IntegerField(choices=[(4, 'Viúvo'), (1, 'Solteiro'), (5, 'União Estável'), (2, 'Casado'), (3, 'Divorciado')]),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(2, 'Masculino'), (1, 'Femino'), (3, 'Não Binário')], null=True),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='raca',
            field=models.IntegerField(choices=[(6, 'Não Declarado'), (5, 'Indígena'), (2, 'Branca'), (1, 'Preta'), (3, 'Amarela (Origem Asiática/Oriental)'), (4, 'Parda')]),
        ),
        migrations.AlterField(
            model_name='redesocial',
            name='tipo',
            field=models.IntegerField(choices=[(8, 'OUtras'), (4, 'Instagram'), (5, 'PodCast'), (3, 'Youtube'), (2, 'Facebook'), (1, 'Site/Blog'), (7, 'Twitter'), (6, 'LinkedIn')]),
        ),
        migrations.AlterField(
            model_name='veiculodecomunicacao',
            name='tipo',
            field=models.IntegerField(choices=[(3, 'Rádio'), (7, 'Plataforma de Video'), (8, 'Podcast'), (2, 'Revista'), (1, 'Jornal'), (5, 'Site/Blog'), (4, 'TV'), (6, 'Rede Social')]),
        ),
    ]
