# Generated by Django 4.0.5 on 2022-07-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiretorioJornalistas', '0007_alter_jornalista_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='estado_civil',
            field=models.IntegerField(choices=[(1, 'Solteiro'), (3, 'Divorciado'), (5, 'União Estável'), (2, 'Casado'), (4, 'Viúvo')]),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='raca',
            field=models.IntegerField(choices=[(5, 'Indígena'), (2, 'Branca'), (4, 'Parda'), (1, 'Preta'), (6, 'Não Declarado'), (3, 'Amarela (Origem Asiática/Oriental)')]),
        ),
        migrations.AlterField(
            model_name='redesocial',
            name='tipo',
            field=models.IntegerField(choices=[(2, 'Facebook'), (4, 'Instagram'), (1, 'Site/Blog'), (6, 'LinkedIn'), (8, 'OUtras'), (3, 'Youtube'), (5, 'PodCast'), (7, 'Twitter')]),
        ),
        migrations.AlterField(
            model_name='veiculodecomunicacao',
            name='tipo',
            field=models.IntegerField(choices=[(4, 'TV'), (1, 'Jornal'), (5, 'Site/Blog'), (3, 'Rádio'), (2, 'Revista'), (6, 'Rede Social'), (7, 'Plataforma de Video'), (8, 'Podcast')]),
        ),
    ]
