# Generated by Django 3.2.8 on 2021-10-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleDeAcesso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (4, 'Usuario'), (2, 'Revisor'), (3, 'Jornalista')], null=True),
        ),
    ]
