# Generated by Django 3.2.7 on 2021-10-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleDeAcesso', '0002_auto_20211025_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.IntegerField(blank=True, choices=[(3, 'Jornalista'), (4, 'Usuario'), (1, 'Admin'), (2, 'Revisor')], null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(3, 'Não Binário'), (1, 'Femino'), (2, 'Masculino')], null=True),
        ),
    ]
