# Generated by Django 3.2.8 on 2021-10-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleDeAcesso', '0002_alter_usuario_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.IntegerField(choices=[(2, 'Revisor'), (1, 'Admin'), (3, 'Jornalista'), (4, 'Usuario')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='raça_etnia',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
