# Generated by Django 3.2.8 on 2021-10-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleDeAcesso', '0003_auto_20211011_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.IntegerField(choices=[(4, 'Usuario'), (2, 'Revisor'), (1, 'Admin'), (3, 'Jornalista')]),
        ),
    ]
