# Generated by Django 3.2.8 on 2021-10-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleDeAcesso', '0005_auto_20211011_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.IntegerField(blank=True, choices=[(4, 'Usuario'), (1, 'Admin'), (2, 'Revisor'), (3, 'Jornalista')], null=True),
        ),
    ]
