# Generated by Django 3.2.7 on 2021-11-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleDeAcesso', '0005_auto_20211102_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (3, 'Jornalista'), (4, 'Usuario'), (2, 'Revisor')], null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='raca_etnia',
            field=models.IntegerField(blank=True, choices=[(3, 'Amarela (Origem Asiática/Oriental)'), (4, 'Parda'), (5, 'Indígena'), (6, 'Não Declarado'), (2, 'Branca'), (1, 'Preta')], null=True),
        ),
    ]
