# Generated by Django 3.2.7 on 2021-11-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleDeAcesso', '0006_auto_20211102_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.IntegerField(blank=True, choices=[(2, 'Revisor'), (1, 'Admin'), (3, 'Jornalista'), (4, 'Usuario')], null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(1, 'Femino'), (3, 'Não Binário'), (2, 'Masculino')], null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='raca_etnia',
            field=models.IntegerField(blank=True, choices=[(3, 'Amarela (Origem Asiática/Oriental)'), (6, 'Não Declarado'), (5, 'Indígena'), (2, 'Branca'), (4, 'Parda'), (1, 'Preta')], null=True),
        ),
    ]
