version: '3.3'

services:
  web:
    build: .
    volumes:
      - .:/src
    restart: always
    env_file:
      - ./apiDiretorioJornalistas/.env
    command: ["bash", "start_server.sh"]
    ports: [8000:8000]