# Generated by Django 3.2.7 on 2021-10-26 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('tema', models.CharField(max_length=65, primary_key=True, serialize=False)),
                ('instituicao', models.CharField(max_length=65)),
                ('ano_conclusao', models.DateField()),
                ('nivel_graduacao', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=50)),
                ('fala', models.IntegerField(blank=True, choices=[(4, 'Fluente'), (3, 'Bem'), (1, 'Pouco'), (2, 'Razoavelmente')], null=True)),
                ('ler', models.IntegerField(blank=True, choices=[(4, 'Fluente'), (3, 'Bem'), (1, 'Pouco'), (2, 'Razoavelmente')], null=True)),
                ('escreve', models.IntegerField(blank=True, choices=[(4, 'Fluente'), (3, 'Bem'), (1, 'Pouco'), (2, 'Razoavelmente')], null=True)),
                ('compreende', models.IntegerField(blank=True, choices=[(4, 'Fluente'), (3, 'Bem'), (1, 'Pouco'), (2, 'Razoavelmente')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalDeTrabalho',
            fields=[
                ('nome_profissinal', models.CharField(max_length=65, primary_key=True, serialize=False)),
                ('registro_profissional', models.CharField(blank=True, max_length=65, null=True)),
                ('empresa_instituicao', models.CharField(blank=True, max_length=65, null=True)),
                ('contato_do_jornalista', models.CharField(blank=True, max_length=65, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulos', models.CharField(blank=True, max_length=100, null=True)),
                ('outros_aspectos_profissionais', models.CharField(blank=True, max_length=255, null=True)),
                ('locais_de_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.localdetrabalho')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('exp_profissional', models.ManyToManyField(blank=True, related_name='exp_profissional', to='curriculo.ExpProfissional')),
                ('formacao', models.ManyToManyField(blank=True, related_name='formacao', to='curriculo.Formacao')),
                ('idioma', models.ManyToManyField(blank=True, related_name='idioma', to='curriculo.ExpProfissional')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
