# Generated by Django 3.2.7 on 2021-10-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='exp_profissional',
            field=models.ManyToManyField(blank=True, to='curriculo.ExpProfissional'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='formacao',
            field=models.ManyToManyField(blank=True, to='curriculo.Formacao'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='idioma',
            field=models.ManyToManyField(blank=True, to='curriculo.Idioma'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='compreende',
            field=models.IntegerField(blank=True, choices=[(4, 'Fluente'), (2, 'Razoavelmente'), (1, 'Pouco'), (3, 'Bem')], null=True),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='escreve',
            field=models.IntegerField(blank=True, choices=[(4, 'Fluente'), (2, 'Razoavelmente'), (1, 'Pouco'), (3, 'Bem')], null=True),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='fala',
            field=models.IntegerField(blank=True, choices=[(4, 'Fluente'), (2, 'Razoavelmente'), (1, 'Pouco'), (3, 'Bem')], null=True),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='ler',
            field=models.IntegerField(blank=True, choices=[(4, 'Fluente'), (2, 'Razoavelmente'), (1, 'Pouco'), (3, 'Bem')], null=True),
        ),
    ]
