# Generated by Django 4.0.6 on 2022-07-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornalista',
            name='historico_profissional',
            field=models.ManyToManyField(to='historico.historicoprofissional'),
        ),
    ]
