# Generated by Django 4.0.6 on 2022-07-24 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
        ('autenticacao', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opcoes', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornalista',
            name='obras_jornalisticas',
            field=models.ManyToManyField(to='obras.obrajornalistica'),
        ),
        migrations.AddField(
            model_name='jornalista',
            name='rede_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcoes.redessociais'),
        ),
        migrations.AddField(
            model_name='jornalista',
            name='revisor_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autenticacao.revisor'),
        ),
        migrations.AddField(
            model_name='jornalista',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='associacao',
            name='rede_sociais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.redessociais'),
        ),
    ]
