# Generated by Django 4.0.5 on 2022-09-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_remove_associacao_rede_sociais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornalista',
            name='revisor_responsavel',
        ),
    ]
