# Generated by Django 4.1.3 on 2022-11-21 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0006_remove_jornalista_revisor_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornalista',
            name='etnia',
        ),
    ]
