# Generated by Django 4.1.3 on 2022-11-21 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcoes', '0002_cidades_estados_delete_etnia_cidades_estado'),
        ('autenticacao', '0007_remove_jornalista_etnia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.cidades'),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='ddd_telefone',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.estados'),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.estadocivil'),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='registro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='telefone',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
