# Generated by Django 4.1.3 on 2022-12-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0008_alter_jornalista_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornalista',
            name='ddd_telefone',
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
