# Generated by Django 4.1.3 on 2022-12-21 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcoes', '0002_cidades_estados_delete_etnia_cidades_estado'),
        ('autenticacao', '0009_remove_jornalista_ddd_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornalista',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.genero'),
        ),
    ]
