# Generated by Django 4.1.3 on 2022-12-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcoes', '0002_cidades_estados_delete_etnia_cidades_estado'),
        ('autenticacao', '0010_alter_jornalista_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornalista',
            name='rede_social',
            field=models.ManyToManyField(to='opcoes.redessociais'),
        ),
    ]
