# Generated by Django 4.1.3 on 2022-12-21 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0011_jornalista_rede_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornalista',
            name='rede_social',
        ),
    ]
