# Generated by Django 3.2.7 on 2021-11-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleDeAcesso', '0004_auto_20211102_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.IntegerField(blank=True, choices=[(3, 'Jornalista'), (1, 'Admin'), (2, 'Revisor'), (4, 'Usuario')], null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(2, 'Masculino'), (1, 'Femino'), (3, 'Não Binário')], null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='raca_etnia',
            field=models.IntegerField(blank=True, choices=[(4, 'Parda'), (1, 'Preta'), (2, 'Branca'), (5, 'Indígena'), (3, 'Amarela (Origem Asiática/Oriental)'), (6, 'Não Declarado')], null=True),
        ),
    ]
