# Generated by Django 3.2.7 on 2021-11-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0003_auto_20211102_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='veiculo',
            field=models.IntegerField(choices=[(7, 'Plataforma de Video'), (8, 'Podcast'), (6, 'Rede Social'), (1, 'Jornal'), (5, 'Site/Blog'), (3, 'Rádio'), (2, 'Revista'), (4, 'TV')]),
        ),
        migrations.AlterField(
            model_name='coluna',
            name='veiculo',
            field=models.IntegerField(choices=[(7, 'Plataforma de Video'), (8, 'Podcast'), (6, 'Rede Social'), (1, 'Jornal'), (5, 'Site/Blog'), (3, 'Rádio'), (2, 'Revista'), (4, 'TV')]),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='veiculo',
            field=models.IntegerField(choices=[(7, 'Plataforma de Video'), (8, 'Podcast'), (6, 'Rede Social'), (1, 'Jornal'), (5, 'Site/Blog'), (3, 'Rádio'), (2, 'Revista'), (4, 'TV')]),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='veiculo',
            field=models.IntegerField(choices=[(7, 'Plataforma de Video'), (8, 'Podcast'), (6, 'Rede Social'), (1, 'Jornal'), (5, 'Site/Blog'), (3, 'Rádio'), (2, 'Revista'), (4, 'TV')]),
        ),
        migrations.AlterField(
            model_name='reportagem',
            name='veiculo',
            field=models.IntegerField(choices=[(7, 'Plataforma de Video'), (8, 'Podcast'), (6, 'Rede Social'), (1, 'Jornal'), (5, 'Site/Blog'), (3, 'Rádio'), (2, 'Revista'), (4, 'TV')]),
        ),
        migrations.AlterField(
            model_name='resenha',
            name='veiculo',
            field=models.IntegerField(choices=[(7, 'Plataforma de Video'), (8, 'Podcast'), (6, 'Rede Social'), (1, 'Jornal'), (5, 'Site/Blog'), (3, 'Rádio'), (2, 'Revista'), (4, 'TV')]),
        ),
    ]
