# Generated by Django 4.0.6 on 2022-07-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipodepublicacao',
            old_name='nome',
            new_name='descricao',
        ),
    ]
