# Generated by Django 4.1.3 on 2022-11-21 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcoes', '0002_cidades_estados_delete_etnia_cidades_estado'),
        ('obras', '0003_alter_livro_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.cidades'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.estados'),
        ),
    ]
