# Generated by Django 4.1.3 on 2022-11-21 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0007_remove_jornalista_etnia'),
        ('opcoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=64)),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Etnia',
        ),
        migrations.AddField(
            model_name='cidades',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcoes.estados'),
        ),
    ]
