# Generated by Django 4.1.3 on 2022-12-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcoes', '0002_cidades_estados_delete_etnia_cidades_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redessociais',
            name='link',
            field=models.CharField(max_length=254),
        ),
    ]
