# Generated by Django 3.2.7 on 2021-11-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_auto_20211025_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idioma',
            name='compreende',
            field=models.IntegerField(blank=True, choices=[(2, 'Razoavelmente'), (3, 'Bem'), (1, 'Pouco'), (4, 'Fluente')], null=True),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='escreve',
            field=models.IntegerField(blank=True, choices=[(2, 'Razoavelmente'), (3, 'Bem'), (1, 'Pouco'), (4, 'Fluente')], null=True),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='fala',
            field=models.IntegerField(blank=True, choices=[(2, 'Razoavelmente'), (3, 'Bem'), (1, 'Pouco'), (4, 'Fluente')], null=True),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='ler',
            field=models.IntegerField(blank=True, choices=[(2, 'Razoavelmente'), (3, 'Bem'), (1, 'Pouco'), (4, 'Fluente')], null=True),
        ),
    ]
