# Generated by Django 3.2.7 on 2021-11-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0002_auto_20211102_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='veiculo',
            field=models.IntegerField(choices=[(4, 'TV'), (3, 'Rádio'), (6, 'Rede Social'), (1, 'Jornal'), (2, 'Revista'), (7, 'Plataforma de Video'), (5, 'Site/Blog'), (8, 'Podcast')]),
        ),
        migrations.AlterField(
            model_name='coluna',
            name='veiculo',
            field=models.IntegerField(choices=[(4, 'TV'), (3, 'Rádio'), (6, 'Rede Social'), (1, 'Jornal'), (2, 'Revista'), (7, 'Plataforma de Video'), (5, 'Site/Blog'), (8, 'Podcast')]),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='veiculo',
            field=models.IntegerField(choices=[(4, 'TV'), (3, 'Rádio'), (6, 'Rede Social'), (1, 'Jornal'), (2, 'Revista'), (7, 'Plataforma de Video'), (5, 'Site/Blog'), (8, 'Podcast')]),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='veiculo',
            field=models.IntegerField(choices=[(4, 'TV'), (3, 'Rádio'), (6, 'Rede Social'), (1, 'Jornal'), (2, 'Revista'), (7, 'Plataforma de Video'), (5, 'Site/Blog'), (8, 'Podcast')]),
        ),
        migrations.AlterField(
            model_name='reportagem',
            name='veiculo',
            field=models.IntegerField(choices=[(4, 'TV'), (3, 'Rádio'), (6, 'Rede Social'), (1, 'Jornal'), (2, 'Revista'), (7, 'Plataforma de Video'), (5, 'Site/Blog'), (8, 'Podcast')]),
        ),
        migrations.AlterField(
            model_name='resenha',
            name='veiculo',
            field=models.IntegerField(choices=[(4, 'TV'), (3, 'Rádio'), (6, 'Rede Social'), (1, 'Jornal'), (2, 'Revista'), (7, 'Plataforma de Video'), (5, 'Site/Blog'), (8, 'Podcast')]),
        ),
    ]
