# Generated by Django 3.2.7 on 2021-11-02 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicacao', '0004_auto_20211102_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artigo',
            name='veiculo',
            field=models.IntegerField(choices=[(6, 'Rede Social'), (7, 'Plataforma de Video'), (4, 'TV'), (1, 'Jornal'), (8, 'Podcast'), (2, 'Revista'), (3, 'Rádio'), (5, 'Site/Blog')]),
        ),
        migrations.AlterField(
            model_name='coluna',
            name='veiculo',
            field=models.IntegerField(choices=[(6, 'Rede Social'), (7, 'Plataforma de Video'), (4, 'TV'), (1, 'Jornal'), (8, 'Podcast'), (2, 'Revista'), (3, 'Rádio'), (5, 'Site/Blog')]),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='veiculo',
            field=models.IntegerField(choices=[(6, 'Rede Social'), (7, 'Plataforma de Video'), (4, 'TV'), (1, 'Jornal'), (8, 'Podcast'), (2, 'Revista'), (3, 'Rádio'), (5, 'Site/Blog')]),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='veiculo',
            field=models.IntegerField(choices=[(6, 'Rede Social'), (7, 'Plataforma de Video'), (4, 'TV'), (1, 'Jornal'), (8, 'Podcast'), (2, 'Revista'), (3, 'Rádio'), (5, 'Site/Blog')]),
        ),
        migrations.AlterField(
            model_name='reportagem',
            name='veiculo',
            field=models.IntegerField(choices=[(6, 'Rede Social'), (7, 'Plataforma de Video'), (4, 'TV'), (1, 'Jornal'), (8, 'Podcast'), (2, 'Revista'), (3, 'Rádio'), (5, 'Site/Blog')]),
        ),
        migrations.AlterField(
            model_name='resenha',
            name='veiculo',
            field=models.IntegerField(choices=[(6, 'Rede Social'), (7, 'Plataforma de Video'), (4, 'TV'), (1, 'Jornal'), (8, 'Podcast'), (2, 'Revista'), (3, 'Rádio'), (5, 'Site/Blog')]),
        ),
    ]
